language: ruby
sudo: false
cache: bundler
script: "bundle exec rake ci"
rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby
  - jruby-head
  - jruby-19mode # JRuby in 1.9 mode
env:
  global:
    - CODECLIMATE_REPO_TOKEN=bff5110004e542a78ce5dd5fb7f154ac06cdc5a564d54957656a56e79bf1a031
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6efc69df9417bda7808
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
